;; Do not edit this file manually! Run emacs.d/bin/update-emacs-packages.el
'(color-theme-solarized color-theme flycheck let-alist pkg-info epl dash sass-mode haml-mode scss-mode undo-tree web-mode zencoding-mode)
